name: publish CI

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        required: true
        description: 'Release Type'
        options:
          - Full
          - Patch
          - Update
      new_version:
        description: "New Netkit Version (Without 'v' Ex: 1.0.0)"
        required: true
        type: string
      prev_version:
        description: "Previous Netkit Version (Without 'v' Ex: 1.0.0): Important for Patch and Update"
        required: true
        type: string

env:
  RELEASE_TYPE: ${{ inputs.release_type }}
  NEW_VERSION: ${{ inputs.new_version }}
  PREV_VERSION: ${{ inputs.prev_version }}
  REPO_NAME: ${{ github.event.repository.name }}
  MODULE_NAME: "netkit"

jobs:

  MavenRelease:
    environment: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo and clone to CI workspace
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Copy and Decode
        run: |
            mkdir $PWD/.kltrenv && echo "${{ secrets.SIGNING_KEY }}" > $PWD/.kltrenv/secring.gpg.b64
            base64 -d $PWD/.kltrenv/secring.gpg.b64 > $PWD/.kltrenv/secring.gpg

      - name: Gradle Build...
        run: ./gradlew build

      - name: Run publish Script
        run: |
          RELEASE_TYPE=${RELEASE_TYPE} NEW_VERSION=${NEW_VERSION}
          PREV_VERSION=${PREV_VERSION} REPO_NAME=${REPO_NAME}
          TOKEN=${{ secrets.GITHUB_TOKEN }} MODULE_NAME=${MODULE_NAME} TEAMS_WEBHOOK=${{ secrets.TEAMSWEBHOOK }} bash .github/publish.sh

      - name: Delete secring file
        run: |
            rm -rf $PWD/.kltrenv
